include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: false
    avoid_types_as_parameter_names: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    curly_braces_in_flow_control_structures: false
    depend_on_referenced_packages: true
    hash_and_equals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    unnecessary_this: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_string_buffers: true
    use_super_parameters: true
    sort_pub_dependencies: true
    omit_local_variable_types: false
    prefer_if_elements_to_conditional_expressions: false
    avoid_bool_literals_in_conditional_expressions: true
    noop_primitive_operations: true
    prefer_final_locals: true
    unnecessary_await_in_return: true
    sort_constructors_first: true
    sized_box_shrink_expand: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    cascade_invocations: true
    unawaited_futures: true
    unnecessary_lambdas: true
    use_named_constants: true
    parameter_assignments: false
    avoid_void_async: true
    prefer_null_aware_method_calls: true
    avoid_slow_async_io: true
    avoid_field_initializers_in_const_classes: true
    cast_nullable_to_non_nullable: true
    unnecessary_null_checks: true
    avoid_escaping_inner_quotes: true
    join_return_with_assignment: true
    use_setters_to_change_properties: true
    avoid_unused_constructor_parameters: true
    only_throw_errors: true
    no_default_cases: true