/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
library platform_adaptivity;

import 'package:flutter/widgets.dart';

@staticIconProvider
abstract final class AppIcons {
  const AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String _kFontPkg = 'platform_adaptivity';

  static const IconData binocularsfill = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bivital = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubbleleft = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buground = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData continuouspage = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData continuouspagealt = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData csv = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dayandnight = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dayandnightoutlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropdownup = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ecgheartcupertino = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ecgheartmaterial = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData externallink = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritefill = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoriteslash = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoriteslashfill = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figurerun = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutter = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gearfill = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontalscrolling = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imagesstack = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mp3 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nobug = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nosignal = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagebypage = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagebypagealt = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prize = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puzzle = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rabbitfill = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsfill = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperaturesensor = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tortoisefill = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalscrolling = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vitalsigns = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waveformpathecgrectangle = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zip = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
